server:
  port: 9002
spring:
  application:
    name: communitygroup-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.248.48.100:3306/tensquare_recruit?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  data:
    mongodb:
      host: 121.248.48.100
      database: recruitdb
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true