server:
  port: 9008
spring:
  application:
    name: communitygroup-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.248.48.100:3306/tensquare_user?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  rabbitmq:
    host: 121.248.48.100
  redis:
    host: 121.248.48.100