server:
  port: 9005
spring:
  application:
    name: communitygroup-gathering
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.248.48.100:3306/tensquare_gathering?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 192.168.245.128