server:
  port: 12000
spring:
  application:
    name: communitygroup-configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/songwell1024/config-repo.git
  rabbitmq:
    host: 121.248.48.100
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true
