server:
  port: 9006
spring:
  application:
    name: communitygroup-spit
  data:
    mongodb:
      host: 121.248.48.100
      database: spitdb
  redis:
    host: 121.248.48.100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true